# Generated by Django 5.1.7 on 2025-03-13 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 13, 5, 52, 8, 163695, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
